name: VCMI

on:
  push:
    branches:
      - beta
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.platform }})
    strategy:
      matrix:
        include:
          - platform: msvc-x64
            arch: x64
            toolset: '14.29'
            os: windows-2025
            pack: 1
            upload: 0
            pack_type: RelWithDebInfo
            extension: zip
            preset: windows-msvc-ninja-release
            conan_profile: msvc-x64
            conan_prebuilts: dependencies-windows-x64
            conan_options: -s "&:build_type=RelWithDebInfo" -c tools.env.virtualenv:powershell=pwsh -o "&:target_pre_windows10=True"
            artifact_platform: x64

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Prepare CI
      if: "${{ matrix.before_install != '' }}"
      run: source '${{github.workspace}}/CI/before_install/${{matrix.before_install}}' '${{matrix.arch}}'

    - name: Install Conan Dependencies
      if: "${{ matrix.conan_prebuilts != '' }}"
      run: |
        pipx install conan
        source '${{github.workspace}}/CI/install_conan_dependencies.sh' '${{matrix.conan_prebuilts}}'

    - name: Setup MSVC Developer Command Prompt
      if: ${{ startsWith(matrix.platform, 'msvc') }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
        toolset: ${{ matrix.toolset }}

    # ensure the cache for each PR is separate so they don't interfere with each other
    # fall back to cache of the vcmi/vcmi repo if no PR-specific cache is found

    - name: Setup compiler cache for PRs
      uses: hendrikmuhs/ccache-action@v1.2
      if: ${{ github.event.number != '' }}
      with:
        variant: ${{ startsWith(matrix.platform, 'msvc') && 'sccache' || 'ccache' }}
        key: ${{ matrix.platform }}-PR-${{ github.event.number }}
        restore-keys: |
          ${{ matrix.platform }}-PR-${{ github.event.number }}
          ${{ matrix.platform }}-branch-${{ github.base_ref }}
          ${{ matrix.platform }}-
        create-symlink: ${{ !startsWith(matrix.platform, 'msvc') }}
        max-size: '5G'
        verbose: 2
        job-summary: ""           # <-- disable built-in summary to avoid duplicate block

    - name: Setup compiler cache for branch builds
      uses: hendrikmuhs/ccache-action@v1.2
      if: ${{ github.event.number == '' }}
      with:
        variant: ${{ startsWith(matrix.platform, 'msvc') && 'sccache' || 'ccache' }}
        key: ${{ matrix.platform }}-branch-${{ github.ref_name }}
        restore-keys: |
          ${{ matrix.platform }}-branch-${{ github.ref_name }}
          ${{ matrix.platform }}-
        create-symlink: ${{ !startsWith(matrix.platform, 'msvc') }}
        max-size: '5G'
        verbose: 2
        job-summary: ""           # <-- disable built-in summary to avoid duplicate block

    - name: Install Conan profile
      if: "${{ matrix.conan_profile != '' }}"
      run: |
        conan profile detect
        outFolder=conan-generated
        conan install . \
          --output-folder="$outFolder" \
          --build=never \
          --profile=dependencies/conan_profiles/${{ matrix.conan_profile }} \
          ${{ matrix.conan_options }}
        ${{ startsWith(matrix.platform, 'msvc') && 'echo CONANRUN_PWSH_SCRIPT="$outFolder/conanrun.ps1" >> $GITHUB_ENV' || '' }}

    - name: Build Number
      run: |
        source '${{github.workspace}}/CI/get_package_name.sh'
        if [ '${{ matrix.artifact_platform }}' ]; then
          VCMI_PACKAGE_FILE_NAME+="-${{ matrix.artifact_platform }}"
        fi
        echo VCMI_PACKAGE_FILE_NAME="$VCMI_PACKAGE_FILE_NAME" >> $GITHUB_ENV
        echo VCMI_PACKAGE_BUILD="$VCMI_PACKAGE_BUILD" >> $GITHUB_ENV
        echo VCMI_PACKAGE_NAME_SUFFIX="$VCMI_PACKAGE_NAME_SUFFIX" >> $GITHUB_ENV
        echo VCMI_PACKAGE_GOLDMASTER="$VCMI_PACKAGE_GOLDMASTER" >> $GITHUB_ENV
      env:
        PULL_REQUEST: ${{ github.event.pull_request.number }}

    - name: Configure (MSVC)
      if: ${{ startsWith(matrix.platform, 'msvc') }}
      run: |
        & $env:CONANRUN_PWSH_SCRIPT

        cmake --preset ${{ matrix.preset }}
      shell: pwsh

    - name: Build
      run: |
        ${{ startsWith(matrix.platform, 'msvc') && '& $env:CONANRUN_PWSH_SCRIPT' }}
        cmake --build --preset ${{matrix.preset}}
      shell: pwsh
      env:
        ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Pack
      id: cpack
      if: ${{ matrix.pack == 1 }}
      run: |
        ${{ startsWith(matrix.platform, 'msvc') && '& $env:CONANRUN_PWSH_SCRIPT' }}
        cd "${{github.workspace}}/out/build/${{matrix.preset}}"
        cpack -C ${{matrix.pack_type}}
      shell: pwsh

    - name: Upload Artifact
      id: upload_artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.VCMI_PACKAGE_FILE_NAME }} - ${{ matrix.platform }}
        compression-level: 9
        path: |
          ${{github.workspace}}/out/build/${{matrix.preset}}/${{ env.VCMI_PACKAGE_FILE_NAME }}.${{ matrix.extension }}

    - name: Upload debug symbols
      id: upload_symbols
      if: ${{ startsWith(matrix.platform, 'msvc') }}
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.VCMI_PACKAGE_FILE_NAME }} - ${{ matrix.platform }} - symbols
        compression-level: 9
        path: |
            ${{github.workspace}}/**/*.pdb
